# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(900, 670)
        Dialog.setStyleSheet("background-color: #fff")
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/res/icon/back1.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setStyleSheet("background-color:#fff;")
        self.widget_2.setObjectName("widget_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 480, 121, 23))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setUnderline(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton#pushButton_2{\n"
"    border:none;\n"
"    background-color: #fff;\n"
"    color:  rgba(46,82,101,200);\n"
"}\n"
"QPushButton#pushButton_2:hover{\n"
"    color: rgba(0,0,0,240);\n"
"}\n"
"QPushButton#pushButton_2:pressed{\n"
"    color: rgba(0,0,0,240);\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setGeometry(QtCore.QRect(80, 410, 281, 61))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton#pushButton{\n"
"    background-color:rgba(255, 255, 255,210);\n"
"    color: rgba(0,0,0,240);\n"
"    border:2px solid rgba(46,82,101,200);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton#pushButton:hover{\n"
"    background-color:rgba(46,82,101,200);\n"
"    color: rgba(250,250,250,210);\n"
"    border:none;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"    background-color:rgba(46,82,101,200);\n"
"    color: rgba(250,250,250,210);\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit.setGeometry(QtCore.QRect(80, 240, 281, 40))
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 40))
        self.lineEdit.setStyleSheet("backgroud-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;\n"
"\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 320, 281, 40))
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.lineEdit_2.setStyleSheet("backgroud-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;\n"
"\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(80, 120, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgba(0,0,0,240);")
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_3.setGeometry(QtCore.QRect(300, 480, 75, 23))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setUnderline(True)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton#pushButton_3{\n"
"    border:none;\n"
"    background-color: #fff;\n"
"    color:  rgba(46,82,101,200);\n"
"}\n"
"QPushButton#pushButton_3:hover{\n"
"    color: rgba(0,0,0,240);\n"
"}\n"
"QPushButton#pushButton_3:pressed{\n"
"    color: rgba(0,0,0,240);\n"
"    font-weight: bold;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.widget_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.pushButton_2.clicked.connect(Dialog.go_to_main) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_2.setText(_translate("Dialog", "다시 메인 화면으로"))
        self.pushButton.setText(_translate("Dialog", "Log In"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "UserName"))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog", "Password"))
        self.label_3.setText(_translate("Dialog", "Log In"))
        self.pushButton_3.setText(_translate("Dialog", "회원가입"))
import resource_rc
